// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dorotec_backend_test.Models;

#nullable disable

namespace dorotecbackendtest.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20221120202223_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dorotec_backend_test.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("Login", "Password");

                    b.ToTable("admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Name = "Administrator",
                            Password = "$argon2id$v=19$m=65536,t=3,p=1$T+3MGwgihMsfgKVUpUy8yw$dy0CMs4pLXLvYuOWjFO3s4DJs77Rj7u5E23VmGjoQJY"
                        });
                });

            modelBuilder.Entity("dorotec_backend_test.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(123)
                        .HasColumnType("nvarchar(123)")
                        .HasColumnName("author");

                    b.Property<int>("Edition")
                        .HasColumnType("int")
                        .HasColumnName("edition");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("nvarchar(63)")
                        .HasColumnName("genre");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(123)
                        .HasColumnType("nvarchar(123)")
                        .HasColumnName("name");

                    b.Property<int>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("pages");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("publish_date");

                    b.HasKey("Id");

                    b.HasIndex("Author", "Name", "Genre", "Edition")
                        .IsUnique();

                    b.ToTable("book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Adele W B Mann",
                            Edition = 10,
                            Genre = "fringilla",
                            Name = "Baker",
                            Pages = 55,
                            Price = 76,
                            PublishDate = new DateTime(2013, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Moses E H Wilson",
                            Edition = 4,
                            Genre = "Donec",
                            Name = "Keaton",
                            Pages = 199,
                            Price = 60,
                            PublishDate = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jonah S N Craft",
                            Edition = 7,
                            Genre = "Nullam",
                            Name = "Candice",
                            Pages = 404,
                            Price = 64,
                            PublishDate = new DateTime(2021, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sandra S Dunn",
                            Edition = 4,
                            Genre = "tellus",
                            Name = "Abra",
                            Pages = 89,
                            Price = 35,
                            PublishDate = new DateTime(2013, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Author = "Madeson C J English",
                            Edition = 5,
                            Genre = "sem.",
                            Name = "Neville",
                            Pages = 202,
                            Price = 59,
                            PublishDate = new DateTime(1998, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Author = "Samantha S Jimenez",
                            Edition = 9,
                            Genre = "turpis",
                            Name = "Owen",
                            Pages = 219,
                            Price = 62,
                            PublishDate = new DateTime(2014, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Author = "Ulla Q Hill",
                            Edition = 7,
                            Genre = "conubia",
                            Name = "Carson",
                            Pages = 328,
                            Price = 44,
                            PublishDate = new DateTime(2011, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Author = "Hilel B Ellis",
                            Edition = 2,
                            Genre = "non",
                            Name = "Aurora",
                            Pages = 434,
                            Price = 80,
                            PublishDate = new DateTime(2011, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Author = "Jeanette R P Mcneil",
                            Edition = 3,
                            Genre = "lacus.",
                            Name = "Lacey",
                            Pages = 393,
                            Price = 54,
                            PublishDate = new DateTime(1998, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Author = "Latifah Daniels",
                            Edition = 1,
                            Genre = "at",
                            Name = "Gil",
                            Pages = 333,
                            Price = 63,
                            PublishDate = new DateTime(2017, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Author = "Emerson Q Peck",
                            Edition = 4,
                            Genre = "Aenean",
                            Name = "Winter",
                            Pages = 489,
                            Price = 58,
                            PublishDate = new DateTime(2006, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Author = "Nissim Church",
                            Edition = 7,
                            Genre = "Aliquam",
                            Name = "Lucian",
                            Pages = 62,
                            Price = 47,
                            PublishDate = new DateTime(2012, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Author = "Fiona Landry",
                            Edition = 8,
                            Genre = "ipsum",
                            Name = "Quintessa",
                            Pages = 168,
                            Price = 53,
                            PublishDate = new DateTime(2001, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Author = "Avram W C Tillman",
                            Edition = 5,
                            Genre = "egestas.",
                            Name = "Stacey",
                            Pages = 301,
                            Price = 76,
                            PublishDate = new DateTime(2015, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Author = "Walker X Browning",
                            Edition = 3,
                            Genre = "et,",
                            Name = "Hilel",
                            Pages = 245,
                            Price = 37,
                            PublishDate = new DateTime(2015, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Author = "Travis L I Houston",
                            Edition = 1,
                            Genre = "augue",
                            Name = "Yasir",
                            Pages = 195,
                            Price = 68,
                            PublishDate = new DateTime(2010, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Author = "Bradley W Fuller",
                            Edition = 4,
                            Genre = "pede",
                            Name = "Austin",
                            Pages = 488,
                            Price = 79,
                            PublishDate = new DateTime(2002, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Author = "Sean V L Gross",
                            Edition = 5,
                            Genre = "Pellentesque",
                            Name = "Leigh",
                            Pages = 259,
                            Price = 61,
                            PublishDate = new DateTime(2017, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Author = "Rajah D E Richmond",
                            Edition = 9,
                            Genre = "tristique",
                            Name = "Omar",
                            Pages = 328,
                            Price = 43,
                            PublishDate = new DateTime(2015, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Author = "Paul Church",
                            Edition = 5,
                            Genre = "tempus",
                            Name = "Maia",
                            Pages = 311,
                            Price = 78,
                            PublishDate = new DateTime(2007, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Author = "Carol Powers",
                            Edition = 4,
                            Genre = "nec",
                            Name = "Ferdinand",
                            Pages = 67,
                            Price = 59,
                            PublishDate = new DateTime(2017, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Author = "Quamar T B Mcdaniel",
                            Edition = 3,
                            Genre = "ante",
                            Name = "Ulysses",
                            Pages = 184,
                            Price = 45,
                            PublishDate = new DateTime(2014, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Author = "Ramona O S Crosby",
                            Edition = 9,
                            Genre = "Aenean",
                            Name = "Alfreda",
                            Pages = 103,
                            Price = 79,
                            PublishDate = new DateTime(2007, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Author = "Perry Q Combs",
                            Edition = 8,
                            Genre = "nunc",
                            Name = "Malik",
                            Pages = 486,
                            Price = 75,
                            PublishDate = new DateTime(2012, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Author = "Dean N Caldwell",
                            Edition = 9,
                            Genre = "Quisque",
                            Name = "Chanda",
                            Pages = 341,
                            Price = 26,
                            PublishDate = new DateTime(2004, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Author = "Quinlan B Holder",
                            Edition = 9,
                            Genre = "Nam",
                            Name = "Lynn",
                            Pages = 455,
                            Price = 31,
                            PublishDate = new DateTime(2016, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Author = "Marvin Q H Mcknight",
                            Edition = 6,
                            Genre = "neque",
                            Name = "Phyllis",
                            Pages = 179,
                            Price = 73,
                            PublishDate = new DateTime(2016, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Author = "Benjamin Trujillo",
                            Edition = 6,
                            Genre = "metus",
                            Name = "Leroy",
                            Pages = 140,
                            Price = 26,
                            PublishDate = new DateTime(2016, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Author = "Dawn C J Workman",
                            Edition = 5,
                            Genre = "a,",
                            Name = "Yetta",
                            Pages = 70,
                            Price = 54,
                            PublishDate = new DateTime(1999, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Author = "Gareth Fuentes",
                            Edition = 6,
                            Genre = "aliquam,",
                            Name = "Garrett",
                            Pages = 340,
                            Price = 44,
                            PublishDate = new DateTime(2004, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            Author = "Eric Thornton",
                            Edition = 6,
                            Genre = "luctus",
                            Name = "Regina",
                            Pages = 234,
                            Price = 58,
                            PublishDate = new DateTime(2004, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            Author = "Martin R S Adkins",
                            Edition = 6,
                            Genre = "lectus",
                            Name = "Denise",
                            Pages = 182,
                            Price = 43,
                            PublishDate = new DateTime(2002, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            Author = "Jacob D Mcguire",
                            Edition = 10,
                            Genre = "lorem.",
                            Name = "Vernon",
                            Pages = 82,
                            Price = 45,
                            PublishDate = new DateTime(2021, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            Author = "Mason Z Sherman",
                            Edition = 4,
                            Genre = "egestas",
                            Name = "Dieter",
                            Pages = 483,
                            Price = 64,
                            PublishDate = new DateTime(2009, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            Author = "Jonah X K Guerrero",
                            Edition = 10,
                            Genre = "faucibus",
                            Name = "Hermione",
                            Pages = 142,
                            Price = 47,
                            PublishDate = new DateTime(1997, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            Author = "India Cummings",
                            Edition = 9,
                            Genre = "arcu",
                            Name = "Lucius",
                            Pages = 400,
                            Price = 55,
                            PublishDate = new DateTime(2019, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            Author = "Lee I Montoya",
                            Edition = 8,
                            Genre = "Proin",
                            Name = "Ivy",
                            Pages = 132,
                            Price = 74,
                            PublishDate = new DateTime(2018, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            Author = "Germaine L M Wells",
                            Edition = 7,
                            Genre = "auctor",
                            Name = "Connor",
                            Pages = 471,
                            Price = 74,
                            PublishDate = new DateTime(2009, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            Author = "Kelsie Castillo",
                            Edition = 4,
                            Genre = "nonummy",
                            Name = "Mariam",
                            Pages = 222,
                            Price = 76,
                            PublishDate = new DateTime(2003, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            Author = "Jillian Salas",
                            Edition = 10,
                            Genre = "rhoncus",
                            Name = "Ursa",
                            Pages = 245,
                            Price = 78,
                            PublishDate = new DateTime(2012, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            Author = "Kennan W Sexton",
                            Edition = 5,
                            Genre = "aliquet",
                            Name = "Jenna",
                            Pages = 467,
                            Price = 76,
                            PublishDate = new DateTime(2001, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            Author = "Ina Romero",
                            Edition = 5,
                            Genre = "sollicitudin",
                            Name = "Samantha",
                            Pages = 252,
                            Price = 64,
                            PublishDate = new DateTime(2021, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            Author = "Wynne Everett",
                            Edition = 8,
                            Genre = "senectus",
                            Name = "Evelyn",
                            Pages = 384,
                            Price = 70,
                            PublishDate = new DateTime(2011, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            Author = "Dustin E Gonzales",
                            Edition = 5,
                            Genre = "faucibus",
                            Name = "Constance",
                            Pages = 462,
                            Price = 74,
                            PublishDate = new DateTime(2002, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            Author = "Aristotle Tillman",
                            Edition = 2,
                            Genre = "non",
                            Name = "Ginger",
                            Pages = 154,
                            Price = 57,
                            PublishDate = new DateTime(2005, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            Author = "Brett D Hess",
                            Edition = 10,
                            Genre = "eu",
                            Name = "Chadwick",
                            Pages = 177,
                            Price = 31,
                            PublishDate = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            Author = "Jocelyn S G Lott",
                            Edition = 8,
                            Genre = "magna.",
                            Name = "Brennan",
                            Pages = 296,
                            Price = 70,
                            PublishDate = new DateTime(2013, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            Author = "Fritz L I Good",
                            Edition = 9,
                            Genre = "et",
                            Name = "Velma",
                            Pages = 133,
                            Price = 66,
                            PublishDate = new DateTime(2007, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            Author = "Stuart R Fulton",
                            Edition = 6,
                            Genre = "feugiat",
                            Name = "Bradley",
                            Pages = 352,
                            Price = 47,
                            PublishDate = new DateTime(2012, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            Author = "Dai R Barton",
                            Edition = 1,
                            Genre = "Nunc",
                            Name = "Eve",
                            Pages = 206,
                            Price = 28,
                            PublishDate = new DateTime(2017, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
