// <auto-generated />
using Livraria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Livraria.Migrations
{
    [DbContext(typeof(LivrariaDb))]
    [Migration("20230519192008_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Livraria.Model.LivrariaModel", b =>
                {
                    b.Property<int>("IdLivro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExemplarLivro")
                        .HasColumnType("int");

                    b.Property<string>("ISBNLivro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TituloLivro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VolumeLivro")
                        .HasColumnType("int");

                    b.HasKey("IdLivro");

                    b.ToTable("Livraria");
                });
#pragma warning restore 612, 618
        }
    }
}
