### BookStore Auth Service
# @name bookstore
@host = http://localhost:5097
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6ImFkbWluIiwiZmFtaWx5X25hbWUiOiIiLCJqdGkiOiIzMmMyOThhMi1mZTVhLTQwNGEtYWVmNS01Nzk2YzhjYmExOWMiLCJleHAiOjE3MDQ2ODU2MTMsImlzcyI6IkRvcm9UZWNoLkJvb2tTdG9yZSIsImF1ZCI6IkRvcm9UZWNoLkJvb2tTdG9yZSJ9.gVKMpd8swwU3L45vPz-kczjABx75vS5qfdAg6W-Zei8

POST {{host}}/api/Authentication/login
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true

{
    "email": "admin@bookstore.com",
    "password": "DoroTech@123"
}

###

# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6ImFkbWluIiwiZmFtaWx5X25hbWUiOiIiLCJqdGkiOiI2ZWY3YWZiZi0yNjZmLTRhMDUtOTdjZC1hNDY0ZmUyODIyMjUiLCJleHAiOjE3MDQ2NjE2OTMsImlzcyI6IkRvcm9UZWNoLkJvb2tTdG9yZSIsImF1ZCI6IkRvcm9UZWNoLkJvb2tTdG9yZSJ9.yflZkvSucDxSkKs4IP0aJKmD_Z6-BXwHAKWZFk5SsEg

POST {{host}}/api/Book
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true
Authorization: Bearer {{token}}

{
  "title": "The FlashPoint Paradox",
  "description": "An history to reboot all DC universe",
  "edition": 1,
  "language": "English",
  "publicationDate": "2010-09-10",
  "cust": 10.0,
  "price": 15.0,
  "itIsFromDonation": false,
  "salePrice": 15.50,
  "isbn": "1092-1209-1092-021",
  "pages": 40
}

###

@id = 7
PUT {{host}}/api/Book/{{id}}
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true
Authorization: Bearer {{token}}

{
  "title": "Justice League: The Flashpoint Paradox",
  "edition": 2,
  "language": "English",
  "publicationDate": "2010-10-30",
  "price": 20,
  "pages": 50
}


###

DELETE {{host}}/api/Book/{{id}}
Authorization: Bearer {{token}}

###
