### BookStore Auth Service
# @name bookstore
@host = http://localhost:5097

POST {{host}}/api/Authentication/login
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true

{
    "email": "admin@bookstore.com",
    "password": "DoroTech@123"
}

###

# needs to update
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6ImFkbWluIiwiZmFtaWx5X25hbWUiOiIiLCJqdGkiOiI3NDc2MTlmZi03NjI5LTRhYTMtYTQxNy1lMTNjOWRlMDhiMTMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJhZG1pbiIsImV4cCI6MTcwNDc2NDU0NSwiaXNzIjoiRG9yb1RlY2guQm9va1N0b3JlIiwiYXVkIjoiRG9yb1RlY2guQm9va1N0b3JlIn0.HlZOgy8ZdfsKx-avbyUKsEitYjWlMcYW4KelsIG9ecA

GET {{host}}/api/Book?%24orderBy=title%20asc&%24skip=5&%24top=5


###

POST {{host}}/api/Book
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true
Authorization: Bearer {{token}}

{
  "title": "The FlashPoint Paradox",
  "author": "DC Comics",
  "description": "An history to reboot all DC universe",
  "edition": 1,
  "language": "English",
  "publicationDate": "2010-09-10",
  "cust": 10.0,
  "price": 15.0,
  "itIsFromDonation": false,
  "salePrice": 15.50,
  "isbn": "1092-1209-1092-021",
  "pages": 40
}

###

@id = 13
PUT {{host}}/api/Book/{{id}}
Content-Type: application/json;odata.metadata=minimal;odata.streaming=true
Authorization: Bearer {{token}}

{
  "title": "Justice League: The Flashpoint Paradox 2",
  "edition": 2,
  "language": "English",
  "publicationDate": "2010-10-30",
  "itIsFromDonation": true,
  "price": 100,
  "pages": 50
}


###

DELETE {{host}}/api/Book/{{id}}
Authorization: Bearer {{token}}

###
